name: Alert `website` repository on `main` push
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Dispatch to `website` repository for regeneration of documents
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          repository: smart-swimmingpool/website
          event-type: doc_update
